// <auto-generated />
using System;
using ControleDeLicitacao.Infrastructure.Persistence.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeLicitacao.Infrastructure.Migrations.Baixa
{
    [DbContext(typeof(BaixaContext))]
    [Migration("20240822155425_ContextoBaixa")]
    partial class ContextoBaixa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.ItemDeReajuste", b =>
                {
                    b.Property<int>("AtaID")
                        .HasColumnType("int");

                    b.Property<int>("ReajusteID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("float");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.HasKey("AtaID", "ReajusteID", "ID");

                    b.HasIndex("ReajusteID");

                    b.ToTable("ItemDeReajuste");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.Reajuste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AtaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Reajuste");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.BaixaLicitacao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime?>("DataAta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Edital")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<int>("OrgaoID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalReajustes")
                        .HasColumnType("int");

                    b.Property<int>("Unidade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Vigencia")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("BaixaLicitacao");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.Empenho", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BaixaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataEmpenho")
                        .HasColumnType("datetime2");

                    b.Property<string>("Edital")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumEmpenho")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("OrgaoID")
                        .HasColumnType("int");

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Unidade")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Empenho");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.ItemDeBaixa", b =>
                {
                    b.Property<int>("BaixaID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("QtdeAEmpenhar")
                        .HasColumnType("float");

                    b.Property<double>("QtdeEmpenhada")
                        .HasColumnType("float");

                    b.Property<double>("QtdeLicitada")
                        .HasColumnType("float");

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("ValorEmpenhado")
                        .HasColumnType("float");

                    b.Property<double>("ValorLicitado")
                        .HasColumnType("float");

                    b.HasKey("BaixaID", "ID", "ValorUnitario");

                    b.ToTable("ItemDeBaixa");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.ItemDeEmpenho", b =>
                {
                    b.Property<int>("EmpenhoID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("BaixaID")
                        .HasColumnType("int");

                    b.Property<bool>("ItemDeBaixa")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("QtdeAEntregar")
                        .HasColumnType("float");

                    b.Property<double>("QtdeEmpenhada")
                        .HasColumnType("float");

                    b.Property<double>("QtdeEntregue")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("ValorEntregue")
                        .HasColumnType("float");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.HasKey("EmpenhoID", "ID");

                    b.ToTable("ItemDeEmpenho");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.NotasEmpenho.EmpenhoPolicia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BaixaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataEmpenho")
                        .HasColumnType("datetime2");

                    b.Property<string>("Edital")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumEmpenho")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumNota")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("EmpenhoPolicia");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.NotasEmpenho.ItemDeNota", b =>
                {
                    b.Property<int>("NotaID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("EmpenhoID")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("QtdeCaixa")
                        .HasColumnType("float");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("ValorCaixa")
                        .HasColumnType("float");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("float");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.HasKey("NotaID", "ID");

                    b.ToTable("ItemDeNota");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.NotasEmpenho.Nota", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BaixaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("Edital")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("EmpenhoID")
                        .HasColumnType("int");

                    b.Property<string>("NumEmpenho")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumNota")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Unidade")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.ItemDeReajuste", b =>
                {
                    b.HasOne("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.Reajuste", "Reajuste")
                        .WithMany("Itens")
                        .HasForeignKey("ReajusteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reajuste");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.ItemDeBaixa", b =>
                {
                    b.HasOne("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.BaixaLicitacao", "Baixa")
                        .WithMany("Itens")
                        .HasForeignKey("BaixaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baixa");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.ItemDeEmpenho", b =>
                {
                    b.HasOne("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.Empenho", "Empenho")
                        .WithMany("Itens")
                        .HasForeignKey("EmpenhoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empenho");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.NotasEmpenho.ItemDeNota", b =>
                {
                    b.HasOne("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.NotasEmpenho.Nota", "Nota")
                        .WithMany("Itens")
                        .HasForeignKey("NotaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.Reajuste", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.BaixaLicitacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.Empenho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Baixa.NotasEmpenho.Nota", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
