// <auto-generated />
using ControleDeLicitacao.Infrastructure.Persistence.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeLicitacao.Infrastructure.Migrations.Item
{
    [DbContext(typeof(ItemContext))]
    partial class ItemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Cadastros.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("EhCesta")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnidadePrimaria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UnidadeSecundaria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.ValueObjects.ItemAssociativo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ItemFilhoID")
                        .HasColumnType("int");

                    b.Property<int>("ItemPaiID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ItemFilhoID");

                    b.HasIndex("ItemPaiID");

                    b.ToTable("ItensAssociativos");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.ValueObjects.ItemNomeAssociativo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.ToTable("NomesAssociativos");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.ValueObjects.ItemAssociativo", b =>
                {
                    b.HasOne("ControleDeLicitacao.Domain.Entities.Cadastros.Item", "ItemFilho")
                        .WithMany()
                        .HasForeignKey("ItemFilhoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleDeLicitacao.Domain.Entities.Cadastros.Item", "ItemPai")
                        .WithMany("ListaItens")
                        .HasForeignKey("ItemPaiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemFilho");

                    b.Navigation("ItemPai");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.ValueObjects.ItemNomeAssociativo", b =>
                {
                    b.HasOne("ControleDeLicitacao.Domain.Entities.Cadastros.Item", "Item")
                        .WithMany("ListaNomes")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Cadastros.Item", b =>
                {
                    b.Navigation("ListaItens");

                    b.Navigation("ListaNomes");
                });
#pragma warning restore 612, 618
        }
    }
}
