// <auto-generated />
using System;
using ControleDeLicitacao.Infrastructure.Persistence.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeLicitacao.Infrastructure.Migrations.Ata
{
    [DbContext(typeof(AtaContext))]
    partial class AtaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.AtaLicitacao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime?>("DataAta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Edital")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<int>("OrgaoID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<double>("TotalLicitado")
                        .HasColumnType("float");

                    b.Property<int>("TotalReajustes")
                        .HasColumnType("int");

                    b.Property<int>("Unidade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Vigencia")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("AtaLicitacao");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.ItemDeAta", b =>
                {
                    b.Property<int>("AtaID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("float");

                    b.HasKey("AtaID", "ID", "ValorUnitario");

                    b.ToTable("ItemDeAta");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.ItemDeReajuste", b =>
                {
                    b.Property<int>("AtaID")
                        .HasColumnType("int");

                    b.Property<int>("ReajusteID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("float");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("float");

                    b.HasKey("AtaID", "ReajusteID", "ID");

                    b.HasIndex("ReajusteID");

                    b.ToTable("ItemDeReajuste");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.Reajuste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AtaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Reajuste");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.ItemDeAta", b =>
                {
                    b.HasOne("ControleDeLicitacao.Domain.Entities.Documentos.Ata.AtaLicitacao", "Ata")
                        .WithMany("Itens")
                        .HasForeignKey("AtaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ata");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.ItemDeReajuste", b =>
                {
                    b.HasOne("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.Reajuste", "Reajuste")
                        .WithMany("Itens")
                        .HasForeignKey("ReajusteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reajuste");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.AtaLicitacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ControleDeLicitacao.Domain.Entities.Documentos.Ata.Reajuste.Reajuste", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
